### ISSUE TITLE
Need Battery/Charger

### ISSUE THREAD

**Issue by Amertz08** [Amertz08/Robot#18]
12V Rechargeable battery and charger that will fit on chassis

**Comment by Amertz08** [comment]
Thinking the following
- [charger](https://www.hobbytown.com/prophet-sport-lipo-ac-battery-charger-3s-3a-35w-by-dynamite-dync2005ca/p390160)
- [battery](https://www.hobbytown.com/3s-lipo-transmitter-battery-pack-11.1v-2600mah-by-gens-ace-ga-b1083/p635644)

**Comment by nBukaty** [comment]
Charger and battery from shop should close this issue.
