### ISSUE TITLE
Solder headers to motor shield

### ISSUE THREAD

**Issue by Amertz08** [Amertz08/Robot#20]
Headers need soldered to motor shield

**Comment by Amertz08** [comment]
1/2 done

**Comment by Amertz08** [comment]
Realized headers should be long enough that they can be accessed on the top of the board for pins not being used by the motor shield

**Comment by nBukaty** [comment]
soldered second shield with long headers

**Comment by nBukaty** [comment]
Soldered second shield with longer headers.
