### ISSUE TITLE
Create basic web app

### ISSUE THREAD

**Issue by Amertz08** [Amertz08/Robot#29]
- [x] Flask app that has 1 route that returns "hello world"
- [x] Dockerfile with python 3.6 as base
- [ ] Dockerfile should install all necessary packages
- [ ] Dockerfile should expose necessary ports
- [x] Dockerfile should have proper command to keep container running on start
- [ ] Container should wait for all necessary previous container to start
- [ ] Add `web` service to `docker-compose.yml` that will bind local code base to allow hot development

Look at #28

**Comment by Hz-Huang** [comment]
Added Dockerfile & basic flask app

**Comment by Amertz08** [comment]
Cool this looks basically g2g. Can you submit a PR for your branch so I can add a couple comments on changes.

**Comment by Amertz08** [comment]
Wait nvm. You still need to `docker-compose` which you noted in your meeting notes. I'll just make my comments here. Expose and run the web app on port `5000` as `80` is the default port for actual web servers such as NGINX. Also on your `pip install` specific a specific Flask version. In our case `0.12.0` will be fine.
