### ISSUE TITLE
Test cases for auth routes

### ISSUE THREAD

**Issue by Amertz08** [Amertz08/Robot#94]
Logic of branches should be tested fully

- [x] - Sign up route
- [x] - Confirm route
- [x] - Resend confirm

**Comment by Hz-Huang** [comment]
I'm not sure why I'm getting fail at this test (https://github.com/Amertz08/Robot/blob/84f390fd7e6c3eaa102464e05a4474e3eb6bcb61/server/web/test_routes.py#L229)
